name: CI

on:
  push:
    - branches: main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4 #clone the repo into runner
      run: docker build -t inisghtflow .
